package ftpCalc

var (
	FTPCALC_ACCT                = `select account_number ,as_of_date  ,busiz_id ,origination_date ,maturity_date ,org_term  ,org_term_mult  ,iso_currency_cd  ,adjustable_type_cd ,org_par_bal ,org_payment_amt ,cur_payment ,cur_net_rate  ,accrual_basis_cd ,amrt_type_cd ,pmt_freq   ,pmt_freq_mult  ,last_payment_date ,next_payment_date ,remain_no_pmts_c ,reprice_freq ,reprice_freq_mult  ,lrd_balance ,last_reprice_date ,next_reprice_date ,domain_id  from   ( select account_number  ,as_of_date  ,busiz_id ,origination_date ,maturity_date ,org_term  ,org_term_mult  ,iso_currency_cd  ,adjustable_type_cd ,org_par_bal   ,org_payment_amt ,cur_payment ,cur_net_rate ,accrual_basis_cd ,amrt_type_cd ,pmt_freq  ,pmt_freq_mult ,last_payment_date  ,next_payment_date ,remain_no_pmts_c  ,reprice_freq  ,reprice_freq_mult ,lrd_balance ,last_reprice_date ,next_reprice_date   ,domain_id  ,row_number() over(order by account_number) rk from mas_ftp_acct_info  where as_of_date = to_date(:1,'YYYY-MM-DD') and domain_id = :2 ) where rk > :3 and rk <= :4`
	FTPCALC_ISJACK              = `select t.dispatch_status from FTP_DISPATCH_PRO t where t.dispatch_id = :1 and t.dispatch_date = to_date(:2,'YYYY-MM-DD')`
	FTPCALC_ACCT_STREAM         = `select account_number,as_of_date,busiz_id,origination_date,maturity_date,org_term,org_term_mult ,iso_currency_cd ,adjustable_type_cd  ,org_par_bal  ,org_payment_amt ,cur_payment   ,cur_net_rate  ,accrual_basis_cd  ,amrt_type_cd  ,pmt_freq  ,pmt_freq_mult ,last_payment_date  ,next_payment_date  ,remain_no_pmts_c ,reprice_freq ,reprice_freq_mult ,lrd_balance  ,last_reprice_date  ,next_reprice_date ,domain_id  from    ( select account_number  ,as_of_date  ,busiz_id  ,origination_date  ,maturity_date ,org_term  ,org_term_mult  ,iso_currency_cd  ,adjustable_type_cd  ,org_par_bal   ,org_payment_amt  ,cur_payment  ,cur_net_rate ,accrual_basis_cd   ,amrt_type_cd  ,pmt_freq   ,pmt_freq_mult ,last_payment_date  ,next_payment_date ,remain_no_pmts_c   ,reprice_freq  ,reprice_freq_mult  ,lrd_balance  ,last_reprice_date  ,next_reprice_date  ,domain_id  ,row_number() over(order by account_number) rk from  HZWY23 where as_of_date = to_date(:1,'YYYY-MM-DD') and domain_id = :2 ) where rk > :3 and rk <= :4`
	FTPCALC_ADJUST_RESERVE      = `select t.busiz_id, t.reserve_percent, t.reserve_rate from ( select t.busiz_id, t.reserve_percent, t.reserve_rate, row_number() over(partition by t.domain_id,t.busiz_id order by t.eff_str_date desc) rk from FTP_ADJUST_CAPITAL_RESERVES t where t.domain_id = :1 and t.eff_str_date <= to_date(:2,'YYYY-MM-DD') and t.eff_end_date > to_date(:3,'YYYY-MM-DD')) t where rk = 1`
	FTPCALC_ADJUST_TERMLIQ      = `select busiz_id, curve_id, reprice_freq_range from FTP_ADJUST_TERM_LIQUIDITY t where domain_id = :1 order by busiz_id`
	FTPCALC_BUSIZ_RULES         = `select t.busiz_id, t.ftp_method_id, t.curve_id, t.term_cd, t.term_cd_mult,t.point_val,t.domain_id from ftp_busiz_method_relation t inner join ftp_busiz_info i on t.domain_id = i.domain_id and t.busiz_id = i.busiz_id and i.ftp_flag = '0' where t.domain_id = :1`
	FTPCALC_INSERT_RESULT       = `insert /*+append+*/ into HZWY23 nologging (domain_id,as_of_date,account_number,ftp_rate,ajust_01,ajust_02,ajust_03,ajust_04) values(:1,to_date(:2,'YYYY-MM-DD'),:3,:4,:5,:6,:7,:8)`
	FTPCALC_CURVE_YIELD         = `select i.as_of_date, n.struct_code, i.yield from mas_curve_define t inner join mas_curve_info_struct_node n  on t.curve_id = n.curve_id  and n.domain_id = t.domain_id inner join mas_curve_info i  on n.uuid = i.curve_uuid where t.domain_id = :1 and t.curve_id = :2 and to_char(i.as_of_date, 'yyyy') = :3 order by i.as_of_date desc`
	FTPCALC_CURVE_YIELD1        = `select curve_id from mas_curve_define t where t.domain_id = :1`
	FTPCALC_CURVE_YIELD2        = `select struct_code, yield, as_of_date from (select n.struct_code, i.yield, i.as_of_date,  dense_rank() over(order by i.as_of_date asc) rk from mas_curve_define t inner join mas_curve_info_struct_node n  on t.curve_id = n.curve_id and n.domain_id = t.domain_id inner join mas_curve_info i on n.uuid = i.curve_uuid where t.domain_id = :1  and t.curve_id = :2 and i.as_of_date >= to_date(:3,'YYYY-MM-DD') ) where rk = 1`
	FTPCALC_DEPOSITION          = `select busiz_id,term_cd,term_cd_mult,weight from ftp_busiz_Redemption_Curve where domain_id = :1 order by busiz_id`
	FTPCALC_DISPATCHINFO        = `select t.input_source_cd,t.output_result_cd from FTP_DISPATCH_LIST t where t.domain_id = :1 and t.dispatch_id= :2`
	FTPCALC_RESULT              = `update FTP_DISPATCH_PRO t set t.dispatch_status = :1,t.err_msg = :2 where t.dispatch_id = :2 and t.dispatch_date = to_date(:3,'YYYY-MM-DD')`
	FTPCALC_CURVE_STRUCT        = `select struct_code,term_cd,term_cd_mult from mas_curve_struct where (domain_id = :1 or 1=1) order by sort_id asc`
	FTPCALC_CUST_CUSTOMPAYMENT  = `select t.pay_amount,t.payment_date,rownum from MAS_FTP_PAYMENT_PLAN t where t.account_number = :1 and t.as_of_date = to_date(:2,'YYYY-MM-DD') order by payment_date asc`
	FTPCALC_CUST_CUSTOMPAYMENT2 = `select t.account_number,t.pay_amount,t.payment_date from MAS_FTP_PAYMENT_PLAN t where as_of_date=to_date(:1,'YYYY-MM-DD') order by t.account_number,t.payment_date asc`
)
